# ----------------------------------------------------------------------------
# Copyright (c) 2017-2021, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

# Generated by Django 2.1.7 on 2019-03-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(help_text='This value is used to sort the display order of the BYOD meeting options')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Workshop')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.MeetingOption'),
        ),
    ]
