# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='foo', max_length=500),
            preserve_default=False,
        ),
    ]
