# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_optionalworkshop_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='draft',
            field=models.BooleanField(default=True, help_text='Draft workshop does not show up on the workshop list overview'),
            preserve_default=False,
        ),
    ]
