# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_workshopdraft_helptext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='closing_date',
        ),
    ]
