# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_workshop_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
