# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_workshop_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sales_open',
            field=models.BooleanField(default=False, help_text='Closed workshops do not show up on the workshop list overview'),
            preserve_default=False,
        ),
    ]
