# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_workshop_sales_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='URL'),
        ),
    ]
