# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_order_datetime_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
