# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_order_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billed_total',
            field=models.CharField(blank=True, default='', help_text='This is the confirmed paid amount from NAU', max_length=300, verbose_name='billed total (USD)'),
            preserve_default=False,
        ),
    ]
