# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:34
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_workshops_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
