# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_workshops_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='public',
            field=models.BooleanField(default=True, help_text='Private workshops will require a custom URL to access and will not be visible on the default Workshop List'),
        ),
    ]
