# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_markdownx'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='private_code',
            field=models.SlugField(default=uuid.uuid4, help_text='This will be the unlock code for your private workshop: https://workshops.qiime.org/?code=<span id="pcode"></span>', max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='public',
            field=models.BooleanField(default=True, help_text='Private workshops will require a custom URL and will not be visible on the default Workshop List'),
        ),
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together=set([('private_code', 'public'), ('title', 'slug')]),
        ),
    ]
