# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_private_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price (USD)'),
        ),
    ]
