# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_order_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='capacity',
        ),
    ]
