# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_remove_workshop_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together=set([('title', 'slug')]),
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='private_code',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='public',
        ),
    ]
