# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_remove_workshop_sales_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='discount',
            new_name='private',
        ),
    ]
